### ISSUE TITLE
Change home title

### ISSUE THREAD

**Issue by JuanAraneta** [deptagency-dar/dar-employee-handbook#14]
![Image](https://user-images.githubusercontent.com/27708904/211319924-021ad273-a6ff-43d0-993a-1e030c8f37fc.png)

We could change it to just `Welcome to Dept® Argentina`

**Comment by flacs5** [comment]
You can do it from Prismic Admin. (this is an Image slice)

**Comment by JuanAraneta** [comment]
Super!
